# Generated by Django 4.0.5 on 2022-08-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_orderitem_product_remove_orderitem_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
