# Generated by Django 4.0.5 on 2022-08-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
